# Example .configuration file that uses the
# Adafruit 160x128 tft color display
#
# This display requires the ESP32, and will not work with the 
#  ESP8266 (at least, not with released code) due to the lack
#  of adequate RAM.
#
substitutions:
  devicename: garage_display
  friendly_name: Garage Display
  device_description: Garage door state display by door

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

spi:    # Use VSPI
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

sensor:
  - platform: uptime
    id: my_uptime

  - platform: wifi_signal
    update_interval: 60s
    id: my_wifi_signal

text_sensor:
  - platform: version
    id: my_version
  - platform: homeassistant
    entity_id: sensor.lastg1reason
    id: last_g1_reason
  - platform: homeassistant
    entity_id: sensor.lastg1time
    id: last_g1_time
  - platform: homeassistant
    entity_id: sensor.lastg2reason
    id: last_g2_reason
  - platform: homeassistant
    entity_id: sensor.lastg2time
    id: last_g2_time

binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.g1_isclosed
    id: garage1_closed
  - platform: homeassistant
    entity_id: binary_sensor.g2_isclosed
    id: garage2_closed

# Place this font file in the same folder as this .yaml file
font:
  - file: 'OpenSans-Regular.ttf'
    id: font1
    size: 10
  - file: 'OpenSans-Regular.ttf'
    id: font2
    size: 24

image:
  - file: "garage1_open.png"
    id: img_garage1_open
    type: RGB24
  - file: "garage1_closed.png"
    id: img_garage1_closed
    type: RGB24
  - file: "garage2_open.png"
    id: img_garage2_open
    type: RGB24
  - file: "garage2_closed.png"
    id: img_garage2_closed
    type: RGB24
  - file: "wifi0.png"
    id: wifi0
    type: RGB24
  - file: "wifi1.png"
    id: wifi1
    type: RGB24
  - file: "wifi2.png"
    id: wifi2
    type: RGB24
  - file: "wifi3.png"
    id: wifi3
    type: RGB24
 
display:
  - platform: st7735
    cs_pin: GPIO16   # These are arbitrarily chosen GPIOs
    dc_pin: GPIO17
    reset_pin: GPIO21
    rotation: 90     # Needed for landscape mode
    lambda: |-
      // Create the display for the Garage Monitor.
      // There will be open/closed door icon, an overall "Open" or "Closed" text,
      //   a timestamp of the last time the garage door was opened or closed (along
      //   with an indicator as to the reason - button press vs. remote), and
      //   a WiFi strength meter.
      //
      // Place the overall Open/Closed text
      if(id(garage1_closed).state && id(garage2_closed).state) {
         it.print(1, 5, id(font2), Color(0,255,0), "Garage Closed");
      } else {
         it.print(5, 5, id(font2), Color(255,0,0), "Garage Open");
      }
      
      // Place the open/closed icons (i.e. images)
      // Garage1 image is 95x60 pixels   Garage2 image is 56x60
      it.image(  4,42,id(garage1_closed).state ? id(img_garage1_closed) : id(img_garage1_open));
      it.image(100,42,id(garage2_closed).state ? id(img_garage2_closed) : id(img_garage2_open));
      
      // Display the WiFi signal strength
      float rssi = id(my_wifi_signal).state;
      it.image(150,0, (rssi<-85) ? id(wifi0) :
                      (rssi<-65) ? id(wifi1) :
                      (rssi<-50) ? id(wifi2) :
                                   id(wifi3));
      
      // Place the time and reason codes for the two garage doors
      // Horizontal position is the middle of each of the .png images
      it.print( 51, 102, id(font1), TextAlign::TOP_CENTER, id(last_g1_time).state.c_str());
      it.print(128, 102, id(font1), TextAlign::TOP_CENTER, id(last_g2_time).state.c_str());
      it.print( 51, 115, id(font1), TextAlign::TOP_CENTER, id(last_g1_reason).state.c_str());
      it.print(128, 115, id(font1), TextAlign::TOP_CENTER, id(last_g2_reason).state.c_str());

status_led:
  pin:
    number: GPIO2
    inverted: False

